import style from './Layout.module.scss';
import { FC, ReactNode } from 'react';
import Head from 'next/head';
import Link from 'next/link';

type LayoutProps = { children?: ReactNode };

function Layout({ children }: LayoutProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={style.bodyContainer}>
        <header className={`${style.header} ${style.layoutTheme}`}>
          <nav className={style.container}>
            <ul className={style.menu}>
              <li className={style.menuItem}>
                <Link href={'/todo'}>
                  <a>Todo</a>
                </Link>
              </li>
            </ul>
          </nav>
        </header>
        <main className={style.container}>{children}</main>
        <footer className={`${style.footer} ${style.layoutTheme}`}>
          Footer
        </footer>
      </div>
    </>
  );
}

export default Layout;
